[tool.poetry]
name = "zalfmas-fbp"
version = "0.2.7"
description = "lib and tooling for Cap'n Proto-based FBP flows"
authors = ["Michael Berg-Mohnicke <michael.berg@zalf.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
zalfmas-common = "^0.1.22"
#zalfmas-common = {path = "../mas_python_common", develop = true}
zalfmas-capnp-schemas = "^0.1.23"
tomli = "^2.2.1"
tomli-w = "^1.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
